// Mirrors the AuditAction enum in apps/backend/prisma/schema.prisma.
export const AUDIT_ACTIONS = [
  'USER_LOGGED_IN',
  'USER_LOGGED_OUT',
  'USER_LOGIN_FAILED',
  'USER_ACCOUNT_LOCKED',
  'USER_PASSWORD_RESET_REQUESTED',
  'USER_PASSWORD_RESET_COMPLETED',
  'USER_INVITED',
  'USER_INVITE_ACCEPTED',
  'USER_ROLE_CHANGED',
  'USER_SUSPENDED',
  'USER_REACTIVATED',
  'USER_REMOVED',
  'DATA_ROOM_CREATED',
  'DATA_ROOM_UPDATED',
  'DATA_ROOM_DELETED',
  'FOLDER_CREATED',
  'FOLDER_RENAMED',
  'FOLDER_MOVED',
  'FOLDER_DELETED',
  'FILE_UPLOADED',
  'FILE_VERSION_UPLOADED',
  'FILE_VIEWED',
  'FILE_DOWNLOADED',
  'FILE_RENAMED',
  'FILE_MOVED',
  'FILE_DELETED',
  'REPORT_EXPORTED',
] as const;

export type AuditActionType = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABELS: Record<AuditActionType, string> = {
  USER_LOGGED_IN: 'User logged in',
  USER_LOGGED_OUT: 'User logged out',
  USER_LOGIN_FAILED: 'Failed login attempt',
  USER_ACCOUNT_LOCKED: 'Account locked',
  USER_PASSWORD_RESET_REQUESTED: 'Password reset requested',
  USER_PASSWORD_RESET_COMPLETED: 'Password reset completed',
  USER_INVITED: 'User invited',
  USER_INVITE_ACCEPTED: 'Invite accepted',
  USER_ROLE_CHANGED: 'Role changed',
  USER_SUSPENDED: 'User suspended',
  USER_REACTIVATED: 'User reactivated',
  USER_REMOVED: 'User removed',
  DATA_ROOM_CREATED: 'Data room created',
  DATA_ROOM_UPDATED: 'Data room updated',
  DATA_ROOM_DELETED: 'Data room deleted',
  FOLDER_CREATED: 'Folder created',
  FOLDER_RENAMED: 'Folder renamed',
  FOLDER_MOVED: 'Folder moved',
  FOLDER_DELETED: 'Folder deleted',
  FILE_UPLOADED: 'File uploaded',
  FILE_VERSION_UPLOADED: 'New version uploaded',
  FILE_VIEWED: 'File previewed',
  FILE_DOWNLOADED: 'File downloaded',
  FILE_RENAMED: 'File renamed',
  FILE_MOVED: 'File moved',
  FILE_DELETED: 'File deleted',
  REPORT_EXPORTED: 'Report exported',
};
